"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const exporter=require("../../../scl90/js/report-export.js");
test("preferred scale is retained when canvas is safe",()=>{const p=exporter.calculateScale({reportWidth:1000,reportHeight:2000,preferredScale:2});assert.equal(p.finalScale,2);assert.equal(p.estimatedCanvasWidth,2000);assert.equal(p.estimatedCanvasHeight,4000);assert.equal(p.reduced,false);});
test("maximum dimension lowers scale",()=>{const p=exporter.calculateScale({reportWidth:100,reportHeight:10000,preferredScale:2,maxArea:1e9});assert.equal(p.finalScale,1.638);assert.ok(p.estimatedCanvasHeight<=16384);});
test("maximum area lowers scale",()=>{const p=exporter.calculateScale({reportWidth:1000,reportHeight:1000,preferredScale:2,maxArea:1000000});assert.equal(p.finalScale,1);assert.ok(p.estimatedCanvasArea<=1000000);});
test("very long mobile report automatically lowers scale",()=>{const p=exporter.calculateScale({reportWidth:390,reportHeight:20000,preferredScale:2});assert.ok(p.finalScale<1);assert.ok(p.estimatedCanvasHeight<=p.maxDimension);assert.ok(p.estimatedCanvasArea<=p.maxArea);});
test("invalid report dimensions fail explicitly",()=>{assert.throws(()=>exporter.calculateScale({reportWidth:0,reportHeight:1000}),error=>error.code==="INVALID_EXPORT_DIMENSIONS");assert.throws(()=>exporter.calculateScale({reportWidth:Number.NaN,reportHeight:1000}),error=>error.code==="INVALID_EXPORT_DIMENSIONS");});
test("report that cannot fit at minimum scale fails instead of truncating",()=>{assert.throws(()=>exporter.calculateScale({reportWidth:1000,reportHeight:40000,preferredScale:2}),error=>error.code==="EXPORT_TOO_LARGE");});
test("export lock rejects concurrent work",async()=>{const lock=exporter.createLock();let release;const first=lock.run(()=>new Promise(resolve=>{release=resolve;}));await assert.rejects(lock.run(async()=>true),error=>error.code==="EXPORT_IN_PROGRESS");release("done");assert.equal(await first,"done");});
test("export lock releases after failure",async()=>{const lock=exporter.createLock();await assert.rejects(lock.run(async()=>{throw new Error("fail");}));assert.equal(lock.active,false);assert.equal(await lock.run(async()=>"retry"),"retry");});
test("filename is neutral and timestamped",()=>{assert.equal(exporter.buildFilename(new Date(2026,8,1,9,7)),"scl90-report-20260901-0907.png");assert.equal(/诊断|确诊|疾病/.test(exporter.buildFilename(new Date())),false);});
test("export exclusion configuration removes actions and development labels",()=>{for(const selector of [".report-actions",".export-exclude","[data-export-exclude]"])assert.ok(exporter.EXCLUDE_SELECTORS.includes(selector));assert.equal(exporter.shouldExclude({matches:s=>s===".report-actions"}),true);assert.equal(exporter.shouldExclude({matches:()=>false}),false);});
function classList(){const set=new Set();return{add:x=>set.add(x),remove:x=>set.delete(x),contains:x=>set.has(x)};}
function environment(){const rootClasses=classList();const htmlClasses=classList();const root={classList:rootClasses,scrollWidth:390,scrollHeight:12000,getBoundingClientRect:()=>({width:390,height:12000})};const anchors=[];const document={fonts:{ready:Promise.resolve()},documentElement:{classList:htmlClasses},body:{appendChild:a=>anchors.push(a)},createElement:()=>({hidden:false,click(){this.clicked=true;},remove(){this.removed=true;}})};const revoked=[];const window={URL:{createObjectURL:()=>"blob:test",revokeObjectURL:url=>revoked.push(url)},setTimeout:fn=>fn()};return{root,document,window,rootClasses,htmlClasses,anchors,revoked};}
test("export mode is always restored after successful rendering",async()=>{const e=environment();let captured;const canvas={width:390,height:12000,toBlob:cb=>cb({size:1234})};const result=await exporter.createPng({...e,preferredScale:1,html2canvas:async(root,options)=>{captured=options;return canvas;},now:new Date(2026,0,1)});assert.equal(result.blobSize,1234);assert.equal(captured.ignoreElements({matches:s=>s===".report-actions"}),true);assert.equal(e.rootClasses.contains("scl90-export-mode"),false);assert.equal(e.htmlClasses.contains("scl90-export-active"),false);});
test("export mode is restored when renderer fails",async()=>{const e=environment();await assert.rejects(exporter.createPng({...e,html2canvas:async()=>{throw new Error("render failed");}}));assert.equal(e.rootClasses.contains("scl90-export-mode"),false);assert.equal(e.htmlClasses.contains("scl90-export-active"),false);});
test("Blob download clicks a temporary link and revokes its URL",async()=>{const e=environment();const canvas={width:390,height:12000,toBlob:cb=>cb({size:222})};const result=await exporter.downloadPng({...e,preferredScale:1,html2canvas:async()=>canvas,now:new Date(2026,8,1,9,7)});assert.equal(result.filename,"scl90-report-20260901-0907.png");assert.equal(e.anchors[0].clicked,true);assert.equal(e.anchors[0].removed,true);assert.deepEqual(e.revoked,["blob:test"]);});
